apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-config.yaml
  - prometheus.yaml
  - grafana.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: sovra-monitoring
    includeSelectors: false
